name: packer
on: 
  pull_request:
    branches:
      - master
    types:
      - opened
      # - edited
      - synchronize
      - closed
jobs:
  packer:
    runs-on: [self-hosted, packer]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.10.3"
      
      - name: Run `packer init`
        id: init
        run: cd packer && packer init .

      - name: Build artifact
        run: cd packer && packer build -color=false -var-file=conception.pkrvars.hcl .